import type { Metadata } from "next";
import { Mulish } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";
import { Toaster } from "./_components/ui/sonner";

const mulish = Mulish({
  subsets: ["latin-ext"]
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={`${mulish.className} antialiased dark`}>
    {/* Provedor de Contexto */}
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      {/* Conteúdo Principal */}
      <main className="flex flex-col overflow-hidden">
        {/* Container Responsivo */}
        <div className="container mx-auto px-4 sm:px-6 lg:px-8">
          {children}
        </div>
      </main>
    </ClerkProvider>

    {/* Toaster para Notificações */}
    <Toaster
      position="bottom-right"
      toastOptions={{
        duration: 5000,
      }}
    />
  </body>
    </html>
  );
}
